# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          pip install coverage coveralls
          sudo apt-get install imagemagick
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup configs
        run: |
          cp server/tests/.svarog.ini.github server/svarog.ini
          mkdir -p ~/.config/svarog-gut

      - name: Coverage
        run: |
          PYTHONPATH=. coverage run --source=svarog_ctl -m pytest -s -v
          coveralls
